/**
 * Inventory — Milestone Two (Receiving & Supplier AP)
 * FROZEN API CONTRACT — request/response schemas.
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │ FROZEN 2026-09-16 (playbook Step 6). Backend and frontend sessions build │
 * │ against this in parallel.                                               │
 * │                                                                         │
 * │ DO NOT edit this file to unblock a build session. If the contract is    │
 * │ wrong: STOP, tell the owner, get the amendment approved, then resume.   │
 * │ All affected sessions stop together. See docs/API_CONTRACT.md §22.      │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * This file is the **source of truth** for the Milestone Two contract.
 * `frontend/features/inventory/types/` mirrors it by hand (there is no pnpm
 * workspace in this repo, so there is no shared package to import from).
 *
 * Plan: `docs/features/inventory/milestone-2-plan.md` §3.
 *
 * All six of the plan's §7 open questions are resolved (owner, 2026-09-16)
 * and reflected in the shapes below — see each schema's own comment for
 * which question it answers:
 *  - Q1 `IN TRANSIT` dropped from `PurchasingSummarySchema` (3 tiles, not 4).
 *  - Q3(a) payment-terms enum unchanged (`INVOICE_TO_FOLLOW` / `PAY_NOW`);
 *    "Invoice" / "Paid on delivery" are UI display labels only.
 *  - Q3(b) `dueDate` is computed once at invoice creation from
 *    `invoiceDate + Supplier.paymentDays` (a real column, migration
 *    `20260916031604_inventory_milestone_two_receiving_ap`) and stored.
 *  - Q4 five-bucket set (`AgingBucketsSchema`) is the single source of truth;
 *    the Supplier detail screen merges the last two for display only.
 *  - Q5 overpayment/credit is modelled (derived, §1.4/§1.5 of the plan) with
 *    no dedicated UI surface this milestone.
 *  - Q6 the Flow 17 reconciliation workspace stays out of scope; the
 *    adjustment endpoint (`CreateInvoiceAdjustmentSchema`) is in, so a
 *    dispute opened by Flow 14 has somewhere to close.
 *
 * Conventions follow Milestone One's `inventory-validators.ts` exactly.
 *
 * Wire-format rule (inherited, non-negotiable): every decimal — quantity,
 * price, total, outstanding — crosses the wire as a **string**, never a JS
 * number. Prisma stores them as Decimal; coercing to number loses precision.
 *
 * AMENDMENT 2026-09-16 (post-freeze, during S3): `PurchasingHistoryRowSchema`
 * added — `GET /inventory/purchasing/history`'s response shape was missed at
 * freeze time despite being called out in plan §3.2/§6.3. See that schema's
 * own comment for detail. No other shape changed.
 *
 * AMENDMENT 2026-09-17 (post-freeze, during S4): `UpdateGoodsReceiptSchema`
 * and `ListGoodsReceiptsQuerySchema` added — the frozen contract named both
 * endpoints (plan §3.2) but never defined their bodies. See each schema's
 * own comment for detail.
 *
 * AMENDMENT 2026-09-17 (New purchase redesign, owner-approved in Paper —
 * `01M1ZZJ6S3FZGF5C7PPBGTKY89`, artboards `X9J-0`/`XXR-0`): supplier becomes
 * **optional** on an expected delivery. The redesigned New-purchase screen
 * lets a Store Manager save a pure shopping list (items + quantities, no
 * supplier assigned yet) — "Save purchase" no longer requires picking a
 * supplier first. Concretely:
 *
 *  - `CreateExpectedDeliverySchema.supplierId` is now `.optional()`.
 *  - `CreateExpectedDeliverySchema.paymentTerms` is now `.optional()` too —
 *    terms describe a relationship with a supplier ("Invoice" / "Paid on
 *    delivery"); they are meaningless with no supplier chosen. The New
 *    Purchase screen greys the payment-terms control out with the caption
 *    "Select a supplier to set payment terms" until a supplier is picked, so
 *    the UI never actually offers terms without a supplier — the schema
 *    matches that by making terms optional rather than defaulting them to
 *    some value nobody chose. **Least-invasive choice over the alternative**
 *    (keep `paymentTerms` required and force a default enum member): a
 *    silently-defaulted payment term on a supplier-less purchase would be
 *    meaningless data sitting in the row, indistinguishable from a real
 *    choice once a supplier is later assigned. Optional + `null` keeps
 *    "nobody has decided this yet" representable.
 *  - `ExpectedDeliverySummarySchema.supplierId` and `.supplierName` become
 *    `.nullable()` (not empty-string sentinels — matches the existing
 *    convention on `estimatedTotal`/`expectedDate`). Wherever a supplier name
 *    would render, a `null` here means literal display copy **"No
 *    supplier"** (service-owned display string, same pattern as
 *    `paymentTermsLabel`/`statusLabel` elsewhere in this file — the
 *    component renders what it's given, it does not invent the fallback
 *    text itself).
 *  - `PurchasingHistoryRowSchema`'s `expectedDelivery` variant already only
 *    carries pre-formatted `supplierName`/`paymentTermsLabel` strings (no
 *    raw ids) — `receiving-service.ts`'s `toHistoryRow` now emits `"No
 *    supplier"` for the name and an empty payment-terms label (rendered as a
 *    dash) when `supplierId` is null. No schema change needed there; only
 *    the service's mapping changes.
 *  - **What-we-owe (Supplier AP) is unaffected by construction, not by a
 *    special case.** Every AP read model (`SupplierApRowSchema`,
 *    `AgingBucketsSchema`, `ApSummarySchema` below) is keyed by
 *    `supplierId` and built by joining `SupplierInvoice`/`SupplierPayment`
 *    rows to a `Supplier` row — `ExpectedDelivery` never feeds them directly
 *    (an AP row exists once a `SupplierInvoice` is recorded against a
 *    signed `GoodsReceipt`, not from the Stage-1 estimate). A supplier-less
 *    `ExpectedDelivery` therefore has no path into an AP query today; §8 of
 *    `receiving-service.test.ts` adds a regression test asserting this stays
 *    true once S7 (AP endpoints) lands, rather than trusting the absence of
 *    code to keep being the reason.
 *  - Prisma: `ExpectedDelivery.supplierId`/`paymentTerms` become nullable
 *    columns (migration `20260917000000_expected_delivery_optional_supplier`,
 *    see `schema.prisma`'s own comment on the model for the same rationale).
 *    `GoodsReceipt`/`SupplierInvoice`/`SupplierPayment` are untouched — a
 *    signed receipt and everything downstream of it still requires a real
 *    supplier; only the Stage-1 *estimate* may be supplier-less.
 *  - `docs/API_CONTRACT.md` §22.5 records this amendment; §22 is otherwise
 *    unchanged.
 *
 * AMENDMENT 2026-09-18 (S6, Receiving worklist redesign, owner-approved in
 * Paper): the Receiving worklist gains a "History" section — a dedicated,
 * filterable, paginated view over the same expectedDelivery/goodsReceipt
 * union `PurchasingHistoryRowSchema` already declares, but reachable by
 * `STORE_ATTENDANT` (the `/inventory/purchasing/history` endpoint is not —
 * see `receiving-routes.ts`'s Purchasing-hub comment). Rather than add
 * `STORE_ATTENDANT` to that route's role list (which would leak
 * `estimatedTotal`/AP status fields the Attendant must never see, per
 * `serializeExpectedDelivery`'s own comment), this adds a parallel endpoint,
 * `GET /inventory/receiving/history`, whose service method reuses the same
 * `toHistoryRow`/new `toGoodsReceiptHistoryRow` mappers with `includeMoney`
 * gated by `canSeeMoney(actor)` exactly like every other endpoint in this
 * file — an Attendant calling this route gets `statusLabel: "Received"` on
 * every `goodsReceipt` row (no AP/invoice/payment status, not even
 * "Cancelled" vs "Disputed" — a single neutral label) and `detailLabel` set
 * to the item summary instead of a KES figure, same convention as
 * `ExpectedDeliverySummarySchema.estimatedTotal`.
 *
 * This also finally resolves the `goodsReceipt` variant of
 * `PurchasingHistoryRowSchema`, declared since the 2026-09-16 amendment but
 * never emitted (`receiving-service.ts`'s `getPurchasingHistory` had an
 * unresolved `TODO(S4): merge in goodsReceipt rows`) — both
 * `/inventory/purchasing/history` and the new `/inventory/receiving/history`
 * now emit real `goodsReceipt` rows, sorted together with `expectedDelivery`
 * rows by date.
 *
 * Real cursor pagination (`cursor`/`hasMore`) is added here rather than
 * repeating `findHistoryRows`'s existing limit-bump gap — `ReceivingHistoryQuerySchema`
 * takes a `cursor` the same shape as `ListExpectedDeliveriesQuerySchema`'s.
 * `docs/API_CONTRACT.md` §22.6 records this amendment.
 *
 * AMENDMENT 2026-09-18 (S8, Suppliers/Supplier-detail frontend build
 * session): three gaps found while building against this contract, closed
 * here rather than left for the frontend to work around:
 *
 *  1. `listSupplierAp` (`GET /inventory/ap/suppliers`) accepted `limit`/
 *     `cursor` on `ListSupplierApQuerySchema` but never applied them — the
 *     service fetched every supplier with an invoice, unbounded, on every
 *     request. No schema change was needed; the service/repository now
 *     apply real cursor pagination (same `take`/`cursor`/`skip: 1` shape as
 *     `goodsReceiptRepository.findAllByOrganization`), and the frontend
 *     infers `hasMore` from `data.length === limit`, the same convention
 *     already used by `use-purchasing-history-list.ts`/
 *     `use-receiving-worklist.ts` for this module's other bare-array list
 *     endpoints — no `hasMore` wrapper field added.
 *  2. `GET /inventory/ap/suppliers/:id` had no response schema or contract
 *     test at all (every other S7 read model has one). `SupplierApDetailSchema`
 *     is added below to close that gap.
 *  3. That same endpoint's response carried no supplier profile fields
 *     (phone/email/contactName/location/paymentDays) and no purchase
 *     history — both named in-scope for Supplier detail (`VND-0`) by plan
 *     §0. `SupplierApDetailSchema.supplier` adds the profile fields
 *     (reusing `SupplierSchema`'s shape from `inventory-validators.ts` plus
 *     `paymentDays`, which is a real `Supplier` column, migration
 *     `20260916031604_inventory_milestone_two_receiving_ap`, that no read
 *     model had exposed until now); `.purchaseHistory` reuses
 *     `GoodsReceiptDetailSchema` via `goodsReceiptRepository.findAllByOrganization`
 *     filtered by `supplierId` — no new query, no new shape.
 */
import { z } from 'zod';

import { supplierPaymentTermsSchema } from './inventory-validators';
import { SupplierSchema } from './supplier-validators';

// --- Shared primitives ------------------------------------------------------

/** A monetary or quantity value on the wire. Always a string (see header). */
const decimalString = z
  .string()
  .regex(/^-?\d+(\.\d+)?$/, 'must be a decimal string');

/** Positive decimal — quantities and prices that cannot be zero or negative. */
const positiveDecimalString = decimalString.refine(
  (v) => Number(v) > 0,
  'must be greater than zero',
);

const uuid = z.string().uuid();
const isoDate = z.string().datetime({ offset: true });

// --- Enums ------------------------------------------------------------------

export const expectedDeliveryStatusSchema = z.enum([
  'AWAITING',
  'FULFILLED',
  'CANCELLED',
]);

/**
 * DRAFT holds an unsigned receipt — `UQE-0` has "Save draft" and "Sign & save"
 * as distinct actions, and Flow 2a's offline path needs it. No ledger rows
 * exist while DRAFT.
 *
 * The RECEIVED_INVOICE_PENDING / RECEIVED_PAID split is the payment-terms
 * branch (01-description.md Stage 2) and decides whether AP is ever created.
 */
export const goodsReceiptStatusSchema = z.enum([
  'DRAFT',
  'RECEIVED_INVOICE_PENDING',
  'RECEIVED_PAID',
  'INVOICE_RECORDED',
  'CANCELLED',
]);

export const supplierInvoiceStatusSchema = z.enum([
  'UNPAID',
  'PARTIALLY_PAID',
  'PAID',
]);

/**
 * Deliberately NOT a member of `supplierInvoiceStatusSchema`. The Supplier
 * detail artboard renders "Disputed" in the same column as "Unpaid"/"Partly
 * paid", but Flow 17a says a disputed invoice still ages and can still be
 * paid — collapsing them makes a disputed-and-partly-paid invoice
 * unrepresentable. See plan §1.3.
 */
export const disputeStatusSchema = z.enum(['OPEN', 'RESOLVED']);

/** CHEQUE: `reference` is the cheque number (required). API_CONTRACT §28.2. */
export const supplierPaymentMethodSchema = z.enum(['BANK', 'CASH', 'MPESA', 'CHEQUE']);

// --- Expected deliveries (Stage 1 — estimates, never a PO) ------------------

export const ExpectedDeliveryLineSchema = z.object({
  id: uuid,
  inventoryItemId: uuid,
  itemName: z.string(),
  /** In the item's BUY unit — the drawer shows "4 crate", "10 unit". */
  quantity: decimalString,
  buyUnit: z.string(),
  /**
   * AMENDMENT: added alongside ExpectedDeliveryDetailSchema — the Goods
   * Receipt entry screen prefills its Receipt Line Grid from this and needs
   * the same "buy: X → usage: Y" conversion label the grid already renders
   * for goods-receipt lines.
   */
  usageUnit: z.string(),
  estimatedUnitPrice: decimalString,
  /** The supplier's own name and code for this item (matched pack line), else null. Ours stays primary. */
  supplierItemName: z.string().nullable(),
  supplierItemCode: z.string().nullable(),
});

export const ExpectedDeliverySummarySchema = z.object({
  id: uuid,
  reference: z.string(),
  /** Null when the purchase was saved with no supplier (AMENDMENT 2026-09-17). */
  supplierId: uuid.nullable(),
  /**
   * Null when `supplierId` is null. Matches the existing nullable-not-
   * sentinel convention (`estimatedTotal`, `expectedDate`) rather than an
   * empty string. Display layers (Purchasing hub Inbound band, History row)
   * render the literal string "No supplier" when this is null — that
   * fallback text lives at the service/component layer, not baked into the
   * wire value.
   */
  supplierName: z.string().nullable(),
  /** Null when `supplierId` is null — terms are meaningless with no supplier chosen. */
  paymentTerms: supplierPaymentTermsSchema.nullable(),
  status: expectedDeliveryStatusSchema,
  /** "Milk, cream, yoghurt · 6 lines" — the DETAIL column. */
  itemSummary: z.string(),
  lineCount: z.number().int(),
  expectedDate: isoDate.nullable(),
  /**
   * NULL FOR STORE_ATTENDANTS BY DESIGN — not merely hidden client-side.
   * `UMS-0`'s Attendant row reads "Milk, cream, yoghurt · 6 lines" where the
   * Manager's identical row on `U7V-0` reads "… · ~KES 8,100". Attendants have
   * zero AP access (01-description.md Stage 10). Plan §3.1.
   */
  estimatedTotal: decimalString.nullable(),
  /** Derived: status = AWAITING AND expectedDate < now(). Never stored. */
  isOverdue: z.boolean(),
  ageLabel: z.string(),
  createdAt: isoDate,
});

/**
 * AMENDMENT (post-freeze): the New Goods Receipt entry screen (`UQE-0`)
 * needs to prefill its supplier/terms/lines from the expected delivery a
 * Receive click carries — the frozen contract only had the list/cancel
 * shapes, never a single-record read with lines. Same summary fields as
 * `ExpectedDeliverySummarySchema` plus the full line array.
 */
export const ExpectedDeliveryDetailSchema = ExpectedDeliverySummarySchema.extend({
  lines: z.array(ExpectedDeliveryLineSchema),
});

export const CreateExpectedDeliverySchema = z.object({
  /** Optional (AMENDMENT 2026-09-17) — a purchase list may be saved with no supplier. */
  supplierId: uuid.optional(),
  /** Optional in lockstep with `supplierId` — see this file's header amendment. */
  paymentTerms: supplierPaymentTermsSchema.optional(),
  expectedDate: isoDate.optional(),
  lines: z
    .array(
      z.object({
        inventoryItemId: uuid,
        quantity: positiveDecimalString,
        estimatedUnitPrice: decimalString,
      }),
    )
    .min(1, 'at least one line is required'),
});

/**
 * AMENDMENT 2026-09-16 (post-freeze, S3 build session): the frozen contract
 * never specified `GET /inventory/purchasing/history`'s response shape,
 * even though plan §3.2/§6.3 call out this exact discriminated-union need
 * (the History band mixes ExpectedDelivery and GoodsReceipt rows in one
 * table). Adding it now, before S5 builds against it, rather than letting
 * S5 reverse-engineer the service's return type. `type` values match what
 * S0's `purchasing-history-row.tsx` component already expects
 * (`expectedDelivery` / `goodsReceipt`, camelCase) — the component was built
 * first and is the harder thing to re-diff, so the wire format conforms to
 * it, not the other way around.
 *
 * This session (S3) can only produce `expectedDelivery` rows for real — no
 * `GoodsReceipt` rows exist until S4. The `goodsReceipt` variant is declared
 * here so S4 only has to start emitting it, not amend the contract again.
 */
const purchasingRowStatusToneSchema = z.enum(['neutral', 'error', 'info']);

const purchasingRowActionSchema = z.object({
  label: z.string(),
  emphasized: z.boolean().optional(),
});

export const PurchasingHistoryRowSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('expectedDelivery'),
    id: uuid,
    supplierName: z.string(),
    paymentTermsLabel: z.string(),
    detailLabel: z.string(),
    ageLabel: z.string(),
    statusLabel: z.string(),
    statusTone: purchasingRowStatusToneSchema,
    actions: z.tuple([purchasingRowActionSchema, purchasingRowActionSchema]),
  }),
  z.object({
    type: z.literal('goodsReceipt'),
    id: uuid,
    title: z.string(),
    subtitleLabel: z.string(),
    detailLabel: z.string(),
    ageLabel: z.string(),
    statusLabel: z.string(),
    statusTone: purchasingRowStatusToneSchema,
    actions: z.tuple([purchasingRowActionSchema, purchasingRowActionSchema]),
  }),
]);

export const ListExpectedDeliveriesQuerySchema = z.object({
  status: expectedDeliveryStatusSchema.optional(),
  supplierId: uuid.optional(),
  search: z.string().trim().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
  cursor: uuid.optional(),
});

/**
 * AMENDMENT 2026-09-17 (post-freeze, UI refinement session): New Purchase's
 * item picker was a flat scrollable dropdown over the whole catalog — poor
 * UX once a supplier has many items. This schema/endpoint feeds a "recently
 * purchased from this supplier" section shown first in a searchable
 * combobox, surfaced before the owner asked for it to become the top of the
 * item list. Sourced from `ExpectedDeliveryLine` (this milestone's own new
 * table — no dependency on GoodsReceipt, which S4 hasn't shipped yet).
 */
export const RecentSupplierItemsQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(20).default(8),
});

export const RecentSupplierItemSchema = z.object({
  inventoryItemId: uuid,
  itemName: z.string(),
  buyUnit: z.string(),
  /** The most recent estimated unit price seen for this item from this supplier. */
  lastUnitPrice: decimalString,
  lastPurchasedAt: isoDate,
});

// --- Goods receipts (Stage 2) ----------------------------------------------

export const GoodsReceiptLineSchema = z.object({
  id: uuid,
  inventoryItemId: uuid,
  itemName: z.string(),
  /** As entered, in the buy unit. */
  quantityBuyUnit: decimalString,
  buyUnit: z.string(),
  /** Converted at save; this is what reached the ledger. */
  quantityUsageUnit: decimalString,
  usageUnit: z.string(),
  unitPrice: decimalString,
  lineTotal: decimalString,
  /** What the goods were bought in; null = not stated. Catalog price matches on this (§28.4). */
  packBuyUnit: z.string().nullable(),
  packSize: decimalString.nullable(),
  /** Stamped at signing: the supplier had lines for the item but none matched, so no catalog price was written. */
  packNotOnFile: z.boolean(),
  supplierItemName: z.string().nullable(),
  supplierItemCode: z.string().nullable(),
  /**
   * Price-alert snapshot. Persisted, never recomputed: by the time the signed
   * receipt is read back, latest-price costing has already overwritten
   * `InventoryItem.currentCost`, so the comparison price is gone. `UVN-0`
   * renders this as a permanent audit record. Plan §1.2.
   */
  priceAlert: z
    .object({
      percentAboveLast: decimalString,
      previousPrice: decimalString,
      acceptedByName: z.string().nullable(),
    })
    .nullable(),
});

export const GoodsReceiptDetailSchema = z.object({
  id: uuid,
  reference: z.string(),
  supplierId: uuid,
  supplierName: z.string(),
  expectedDeliveryId: uuid.nullable(),
  paymentTerms: supplierPaymentTermsSchema,
  status: goodsReceiptStatusSchema,
  supplierDocNumber: z.string().nullable(),
  supplierDocDate: isoDate.nullable(),
  receiptTotal: decimalString,
  lines: z.array(GoodsReceiptLineSchema),
  signature: z
    .object({
      signedByName: z.string(),
      signedByRole: z.string(),
      signedAt: isoDate,
    })
    .nullable(),
  /** `UVN-0`'s "Linked supplier invoice — Not recorded yet" slot. */
  linkedInvoice: z
    .object({ id: uuid, invoiceNumber: z.string() })
    .nullable(),
  createdAt: isoDate,
});

/** `packBuyUnit` / `packSize` are optional: omitted means "not stated" (API_CONTRACT §28.4). */
const receiptLineInput = z.object({
  inventoryItemId: uuid,
  quantityBuyUnit: positiveDecimalString,
  unitPrice: decimalString,
  packBuyUnit: z.string().trim().min(1).max(50).optional(),
  packSize: positiveDecimalString.optional(),
});

export const CreateGoodsReceiptSchema = z.object({
  supplierId: uuid,
  expectedDeliveryId: uuid.optional(),
  paymentTerms: supplierPaymentTermsSchema,
  /** Nullable per Flow 2a — the receipt still saves without it. */
  supplierDocNumber: z.string().trim().min(1).optional(),
  supplierDocDate: isoDate.optional(),
  lines: z
    .array(
      receiptLineInput,
    )
    .min(1, 'at least one line is required'),
});

/**
 * The ledger-writing endpoint. Writes one RECEIVE InventoryTransaction per
 * line at the CENTRAL_STORE location and sets each item's currentCost
 * (latest-price costing), atomically. Plan §1.6.
 */
export const SignGoodsReceiptSchema = z.object({
  pin: z.string().min(4),
  /** Each alerted line must be explicitly accepted — recorded on the line. */
  acceptedPriceAlerts: z.array(uuid).default([]),
});

/**
 * AMENDMENT 2026-09-17 (post-freeze, S4 build session): the frozen contract
 * lists `PATCH /inventory/goods-receipts/:id` (plan §3.2 — "edit a draft
 * only") but never defined its body schema. All fields optional (a partial
 * edit, not a full replace) except `supplierId`, which stays fixed once a
 * receipt exists — changing the supplier on an existing draft would silently
 * invalidate its price-alert comparisons and payment-terms default; a
 * different supplier is a new receipt, not an edit to this one.
 */
export const UpdateGoodsReceiptSchema = z.object({
  expectedDeliveryId: uuid.optional(),
  paymentTerms: supplierPaymentTermsSchema.optional(),
  supplierDocNumber: z.string().trim().min(1).optional(),
  supplierDocDate: isoDate.optional(),
  lines: z
    .array(
      receiptLineInput,
    )
    .min(1, 'at least one line is required')
    .optional(),
});

export const ListGoodsReceiptsQuerySchema = z.object({
  status: goodsReceiptStatusSchema.optional(),
  supplierId: uuid.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
  cursor: uuid.optional(),
});

/**
 * `GET /inventory/receiving/history` (AMENDMENT 2026-09-18, see this file's
 * header). `status` accepts either enum's members since the row union covers
 * both — the service filters the underlying query by whichever type each
 * value belongs to.
 */
export const ReceivingHistoryQuerySchema = z.object({
  search: z.string().trim().min(1).optional(),
  supplierId: uuid.optional(),
  status: z.union([expectedDeliveryStatusSchema, goodsReceiptStatusSchema]).optional(),
  from: isoDate.optional(),
  to: isoDate.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
  cursor: uuid.optional(),
});

// --- Supplier invoices (Stage 10, Flow 14) ---------------------------------

export const SupplierInvoiceSchema = z.object({
  id: uuid,
  supplierId: uuid,
  supplierName: z.string(),
  invoiceNumber: z.string(),
  invoiceDate: isoDate,
  /**
   * Computed once at invoice creation as `invoiceDate + Supplier.paymentDays`
   * and stored — a later change to the supplier's terms must not
   * retroactively shift the due date of an invoice already on the books
   * (plan §1.3, §7 Q3(b)).
   */
  dueDate: isoDate,
  amountBilled: decimalString,
  /** Derived: amountBilled + Σ adjustments − Σ allocations. Plan §1.5. */
  outstanding: decimalString,
  status: supplierInvoiceStatusSchema,
  dispute: z
    .object({
      status: disputeStatusSchema,
      ourFigure: decimalString,
      reason: z.string(),
    })
    .nullable(),
  goodsReceiptIds: z.array(uuid),
  createdAt: isoDate,
});

/**
 * One endpoint for both "Save invoice" and "Record at billed — open dispute"
 * (`UZJ-0`). The third button, "Hold", writes nothing at all — so the only
 * difference between the two write paths is whether an otherwise identical
 * invoice write carries a dispute record. Plan §3.2.
 */
export const CreateSupplierInvoiceSchema = z.object({
  supplierId: uuid,
  /** ≥1 — an invoice may bundle several receipts (Flow 14). */
  goodsReceiptIds: z.array(uuid).min(1),
  invoiceNumber: z.string().trim().min(1),
  invoiceDate: isoDate,
  amountBilled: positiveDecimalString,
  dispute: z
    .object({
      ourFigure: decimalString,
      reason: z.string().trim().min(1),
    })
    .optional(),
});

/** The Accountant's reconciliation adjustment — reason is mandatory (Flow 17). */
export const CreateInvoiceAdjustmentSchema = z.object({
  amount: decimalString,
  reason: z.string().trim().min(1, 'a reason is required'),
});

// --- Supplier payments (Flow 15) -------------------------------------------

export const SupplierPaymentSchema = z.object({
  id: uuid,
  supplierId: uuid,
  amount: decimalString,
  paidAt: isoDate,
  method: supplierPaymentMethodSchema,
  reference: z.string().nullable(),
  allocations: z.array(
    z.object({
      supplierInvoiceId: uuid,
      invoiceNumber: z.string(),
      amount: decimalString,
    }),
  ),
  /** Non-null when this payment reverses another. Payments are immutable. */
  reversalOfId: uuid.nullable(),
  recordedByName: z.string(),
  createdAt: isoDate,
});

/**
 * Overpayment (Σ allocations < amount) is ALLOWED, not an error — the excess
 * becomes a derived supplier credit (Flow 15, plan §1.4).
 */
/** The create response: the payment plus the cheque-number warning (§28.2). */
export const SupplierPaymentCreatedSchema = SupplierPaymentSchema.extend({
  /** True when the same supplier already has a CHEQUE payment with this number. A warning, not an error. */
  duplicateChequeNumber: z.boolean(),
});

export const CreateSupplierPaymentSchema = z
  .object({
    supplierId: uuid,
    amount: positiveDecimalString,
    paidAt: isoDate,
    method: supplierPaymentMethodSchema,
    /** The cheque number when `method` is CHEQUE (then required). */
    reference: z.string().trim().min(1).optional(),
    allocations: z
      .array(
        z.object({
          supplierInvoiceId: uuid,
          amount: positiveDecimalString,
        }),
      )
      .min(1),
  })
  .refine((d) => d.method !== 'CHEQUE' || d.reference !== undefined, {
    message: 'The cheque number is required when paying by cheque',
    path: ['reference'],
  });

export const ReverseSupplierPaymentSchema = z.object({
  reason: z.string().trim().min(1, 'a reason is required'),
});

// --- AP position & aging (derived at query time — plan §1.5) ---------------

/**
 * Five buckets, per `VGE-0`'s "— DAYS OVERDUE —" columns. The Supplier detail
 * panel shows four (merging 61-90 into 60+); see Q4. Aging is by days OVERDUE
 * — i.e. measured from `dueDate`, not from `invoiceDate`.
 */
export const AgingBucketsSchema = z.object({
  current: decimalString,
  days1To30: decimalString,
  days31To60: decimalString,
  days61To90: decimalString,
  days90Plus: decimalString,
});

export const SupplierApRowSchema = z.object({
  supplierId: uuid,
  supplierName: z.string(),
  paymentTerms: supplierPaymentTermsSchema,
  lastInvoiceDate: isoDate.nullable(),
  invoiced: decimalString,
  paid: decimalString,
  outstanding: decimalString,
  buckets: AgingBucketsSchema,
  disputedCount: z.number().int(),
});

export const ApSummarySchema = z.object({
  totalInvoiced: decimalString,
  totalPaid: decimalString,
  totalOutstanding: decimalString,
  supplierCount: z.number().int(),
  suppliersWithBalance: z.number().int(),
});

/**
 * `GET /inventory/ap/suppliers/:id` (`VND-0`) — profile, the what-we-owe
 * bucket panel data (`row`, same derivation `listSupplierAp` uses — plan
 * §1.5's reconciliation invariant), invoice list, payment list, and purchase
 * history. AMENDMENT 2026-09-18 (S8): this schema didn't exist before —
 * every other S7 read model had a frozen response schema and contract test;
 * this endpoint's shape was implicit in the service's return type only.
 * `supplier` reuses `SupplierSchema` (now carrying `paymentDays`, itself a
 * same-day amendment) rather than a bespoke profile shape, since a supplier
 * detail screen's profile fields are identical to the New/edit supplier
 * form's. `purchaseHistory` reuses `GoodsReceiptDetailSchema` — no new
 * query or shape, just `goodsReceiptRepository.findAllByOrganization`
 * filtered by `supplierId` (that filter already existed for S4/S6).
 */
export const SupplierApDetailSchema = z.object({
  supplier: SupplierSchema,
  row: SupplierApRowSchema,
  invoices: z.array(SupplierInvoiceSchema),
  payments: z.array(SupplierPaymentSchema),
  purchaseHistory: z.array(GoodsReceiptDetailSchema),
});

/**
 * Three tiles, not four. `IN TRANSIT` was dropped, not deferred (owner
 * decision 2026-09-16, plan §7 Q1): every purchase in this milestone goes
 * straight from AWAITING to RECEIVED_* in one step, so there's no in-transit
 * state to count. That concept belongs to Milestone Five's branch dispatch.
 */
export const PurchasingSummarySchema = z.object({
  expected: z.object({ count: z.number().int(), overdue: z.number().int() }),
  awaitingInvoice: z.object({
    count: z.number().int(),
    oldestDays: z.number().int().nullable(),
  }),
  owed: z.object({ amount: decimalString, over30Count: z.number().int() }),
});

export const ListSupplierApQuerySchema = z.object({
  search: z.string().trim().min(1).optional(),
  terms: supplierPaymentTermsSchema.optional(),
  hasBalance: z
    .enum(['true', 'false'])
    .transform((v) => v === 'true')
    .optional(),
  agingBucket: z
    .enum(['current', 'days1To30', 'days31To60', 'days61To90', 'days90Plus'])
    .optional(),
  from: isoDate.optional(),
  to: isoDate.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
  cursor: uuid.optional(),
});
