'use client';

import * as React from 'react';
import { useSearchParams } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';

import { useLoader } from '../../../_shared/hooks/use-async';
import { PrintError, PrintFrame } from '../../../dispatch/components/desktop/delivery-note-print-screen';
import { CORRECTION_REASON_TEXT, type DaySheet, type SheetDepartment, type SheetLine } from '../../_shared/types/branch-day-contract';
import { SHEET_ROW, paginateDaySheet, type SheetPage } from '../lib/day-sheet-pages';
import { clock12, kes, longDayYear, qty, shortDayClock } from '../lib/desk-format';
import { branchDayDeskApi } from '../services/branch-day-desk-api';

// The print palette of Paper B13b to B13d (no wds tokens; the sheet is a document, not a screen).
const NAVY = 'text-[#0B2A4A]';
const SLATE = 'text-[#6B7785]';
const BODY = 'text-[#3A4756]';
const RULE = 'bg-[#D5DCE4]';
const LABEL = `font-wds-mono text-[10px] leading-3 tracking-[0.08em] ${SLATE}`;
const COL = `font-wds-mono text-[9px] leading-3 tracking-[0.06em] ${SLATE}`;

const stamp = (iso: string): string => {
  const p = new Intl.DateTimeFormat('en-GB', { timeZone: 'Africa/Nairobi', day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(iso));
  return `${p}, ${clock12(iso)}`;
};

/** The wording of a department's footnote about its corrections: `*`, `**`, one for each corrected line (gap G18). */
const marks = (n: number): string => '*'.repeat(n);

function Logo({ size }: { size: number }) {
  return <div aria-hidden className="shrink-0 rounded-full bg-cover bg-center" style={{ width: size, height: size, backgroundImage: 'url(/images/wendo-logo.jpg)' }} />;
}

function Page({ sheet, number, count, cover, children }: { sheet: DaySheet; number: number; count: number; cover: boolean; children: React.ReactNode }) {
  return (
    <article
      aria-label={`Page ${number} of ${count}`}
      className="relative mx-auto mb-4 flex h-[1123px] w-[794px] max-w-full shrink-0 flex-col overflow-hidden break-after-page border border-[#E3E8EE] bg-white font-wds-sans text-[12px] leading-4 text-[#171512] print:mb-0 print:border-0"
    >
      <div aria-hidden className="h-[10px] shrink-0 bg-[#0B2A4A]" />
      <div className={`flex min-h-0 flex-1 flex-col px-12 ${cover ? 'pt-9' : 'pt-[30px]'}`}>
        {cover ? (
          <>
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3.5">
                <Logo size={52} />
                <div className="flex flex-col gap-0.5">
                  <span className={`text-[18px] font-semibold leading-[22px] ${NAVY}`}>Wendo Coffee Bistro</span>
                  <span className={`text-[12px] leading-4 ${SLATE}`}>{sheet.branch.name} · Branch day sheet</span>
                </div>
              </div>
              <div className="flex flex-col items-end gap-0.5">
                <span className={LABEL}>DAY SHEET</span>
                <span className={`font-wds-mono text-[26px] font-semibold leading-8 ${NAVY}`}>{sheet.reference}</span>
                <span className={`text-[12px] leading-4 ${SLATE}`}>{longDayYear(sheet.date)}</span>
              </div>
            </div>
            <div aria-hidden className={`my-5 h-px shrink-0 ${RULE}`} />
          </>
        ) : (
          <>
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <Logo size={36} />
                <div className="flex flex-col gap-px">
                  <span className={`text-[14px] font-semibold leading-[18px] ${NAVY}`}>Wendo Coffee Bistro</span>
                  <span className={`text-[11px] leading-[14px] ${SLATE}`}>{sheet.branch.name} · Branch day sheet</span>
                </div>
              </div>
              <div className="flex flex-col items-end gap-px">
                <span className={`font-wds-mono text-[16px] font-semibold leading-5 ${NAVY}`}>{sheet.reference}</span>
                <span className={`text-[11px] leading-[14px] ${SLATE}`}>{longDayYear(sheet.date)}</span>
              </div>
            </div>
            <div aria-hidden className={`mb-[22px] mt-4 h-px shrink-0 ${RULE}`} />
          </>
        )}
        {children}
      </div>
      <footer className="mx-12 flex shrink-0 items-center justify-between border-t border-[#D5DCE4] pb-[18px] pt-[14px]">
        <span className={`text-[10px] leading-[14px] ${SLATE}`}>Generated by Wendo RMS · Designed and developed by Lobster Technologies</span>
        <span className={`font-wds-mono text-[10px] leading-3 ${SLATE}`}>Page {number} of {count}</span>
      </footer>
    </article>
  );
}

function Cover({ sheet, pageOf }: { sheet: DaySheet; pageOf: number[] }) {
  const info = [
    ['Closed', shortDayClock(sheet.closedAt)],
    ...(sheet.correctedAt ? [['Corrected', shortDayClock(sheet.correctedAt)]] : []),
    ['Printed', shortDayClock(sheet.printedAt)],
  ] as const;
  const head = `${COL} `;
  return (
    <>
      <div className="flex gap-10">
        <div className="flex grow flex-col gap-1">
          <span className={LABEL}>BRANCH</span>
          <span className={`text-[14px] font-medium leading-5 ${NAVY}`}>{sheet.branch.name}{sheet.branch.code ? ` (${sheet.branch.code})` : ''}</span>
          <span className={`text-[12px] leading-[18px] ${BODY}`}>Branch Manager: {sheet.closedBy.name}</span>
        </div>
        <dl className="m-0 flex w-[300px] flex-col justify-between gap-1.5 text-[12px] leading-4">
          {info.map(([k, v]) => (
            <div key={k} className="flex justify-between">
              <dt className={SLATE}>{k}</dt>
              <dd className={`m-0 ${NAVY}`}>{v}</dd>
            </div>
          ))}
        </dl>
      </div>

      <table className="mt-7 w-full table-fixed border-collapse" aria-label="Departments">
        <colgroup>
          <col className="w-[22px]" />
          <col />
          <col className="w-[84px]" />
          <col className="w-[40px]" />
          <col className="w-[78px]" />
          <col className="w-[100px]" />
          <col className="w-[34px]" />
        </colgroup>
        <thead>
          <tr className="border-b-2 border-[#0B2A4A]">
            <th scope="col" className={`${head} pb-2 pr-2.5 text-left font-normal`}>#</th>
            <th scope="col" className={`${head} pb-2 pr-2.5 text-left font-normal`}>DEPARTMENT</th>
            <th scope="col" className={`${head} pb-2 pr-2.5 text-left font-normal`}>HEAD</th>
            <th scope="col" className={`${head} pb-2 pr-2.5 text-right font-normal`}>ITEMS</th>
            <th scope="col" className={`${head} pb-2 pr-2.5 text-right font-normal`}>USED VALUE</th>
            <th scope="col" className={`${head} pb-2 pr-2.5 text-right font-normal`}>CLOSING VALUE</th>
            <th scope="col" className={`${head} pb-2 text-right font-normal`}>PAGE</th>
          </tr>
        </thead>
        <tbody>
          {sheet.departments.map((d, i) => (
            <tr key={d.department.id} className="border-b border-[#E3E8EE]">
              <td className={`py-[11px] pr-2.5 font-wds-mono text-[12px] leading-4 ${SLATE}`}>{d.position}</td>
              <td className={`py-[11px] pr-2.5 text-[13px] font-medium leading-4 ${NAVY}`}>
                {d.department.name}
                {d.corrected ? ' · corrected' : ''}
              </td>
              <td className={`py-[11px] pr-2.5 text-[12px] leading-4 ${BODY}`}>{d.head?.name ?? '–'}</td>
              <td className={`py-[11px] pr-2.5 text-right font-wds-mono text-[12px] leading-4 ${NAVY}`}>{d.itemCount}</td>
              <td className={`py-[11px] pr-2.5 text-right font-wds-mono text-[12px] leading-4 ${NAVY}`}>{kes(d.usedValueKes)}</td>
              <td className={`py-[11px] pr-2.5 text-right font-wds-mono text-[12px] leading-4 ${NAVY}`}>{kes(d.closingValueKes)}</td>
              <td className={`py-[11px] text-right font-wds-mono text-[12px] leading-4 ${SLATE}`}>{pageOf[i]}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="border-b-2 border-[#0B2A4A]">
            <td />
            <td className={`py-3 text-[13px] font-semibold leading-4 ${NAVY}`}>Branch total (KES)</td>
            <td />
            <td className={`py-3 pr-2.5 text-right font-wds-mono text-[12px] font-semibold leading-4 ${NAVY}`}>{sheet.totals.itemCount}</td>
            <td className={`py-3 pr-2.5 text-right font-wds-mono text-[12px] font-semibold leading-4 ${NAVY}`}>{kes(sheet.totals.usedValueKes)}</td>
            <td className={`py-3 pr-2.5 text-right font-wds-mono text-[12px] font-semibold leading-4 ${NAVY}`}>{kes(sheet.totals.closingValueKes)}</td>
            <td />
          </tr>
        </tfoot>
      </table>

      {sheet.corrections.length > 0 ? (
        <section className="mt-[26px] flex flex-col gap-1.5" aria-label="Corrections">
          <span className={LABEL}>{sheet.corrections.length === 1 ? 'CORRECTION' : 'CORRECTIONS'}</span>
          {sheet.corrections.map((c, i) => (
            <p key={`${c.at}-${i}`} className={`m-0 text-[12px] leading-[18px] ${BODY}`}>
              {shortDayClock(c.at)} · {c.departmentName} · {c.itemName} · closing stock {qty(c.fromClosingQty)} → {qty(c.toClosingQty)} · reason: {CORRECTION_REASON_TEXT[c.reason].toLowerCase()} · signed by the Branch Manager.
              {i === sheet.corrections.length - 1 ? ' The figures above include it. The sheet printed at the close is kept on file.' : ''}
            </p>
          ))}
        </section>
      ) : null}

      <section className="mt-5 flex flex-col gap-1" aria-label="Notes">
        <span className={LABEL}>NOTES</span>
        <p className={`m-0 text-[12px] leading-[18px] ${BODY}`}>
          Used today = opening stock + received − waste − closing stock.
          {sheet.notes.openingNotChecked.map((name) => ` ${name}: opening not checked, the day ran on last night’s closing figure.`).join('')}
          {sheet.notes.openDiscrepancies.map((d) => ` ${d.reference} (${d.departmentName}, ${d.itemName}) is open and did not hold the close.`).join('')}
        </p>
      </section>
    </>
  );
}

function Money({ value }: { value: string }) {
  return <span className={Number(value) === 0 ? 'text-[#8A94A3]' : undefined}>{kes(value)}</span>;
}

/** One figure that may carry a correction: the old number struck through in slate, then the corrected one in weight 600 (ruling 6, gap G19). */
function Corrected({ line, field }: { line: SheetLine; field: 'closing' | 'used' }) {
  const now = field === 'closing' ? line.closingQty : line.usedQty;
  const c = line.correction;
  if (!c) return <>{qty(now)}</>;
  const was = field === 'closing' ? c.fromClosingQty : c.fromUsedQty;
  return (
    <>
      <span className="mr-1 text-[#6B7785] line-through">{qty(was)}</span>
      <span className="font-semibold">{qty(now)}</span>
    </>
  );
}

function DepartmentPage({ sheet, department, page, pageNumber, pageCount }: { sheet: DaySheet; department: SheetDepartment; page: Extract<SheetPage, { kind: 'department' }>; pageNumber: number; pageCount: number }) {
  const lines = department.lines.slice(page.from, page.to);
  const correctedLines = department.lines.filter((l) => l.correction);
  const head = department.head?.name ?? '–';
  const counted = department.onBehalf
    ? `Counted by the Branch Manager on behalf of the department at ${clock12(department.countedAt)}`
    : `Head: ${head} · counted ${clock12(department.countedAt)}, signed with PIN`;
  const opening =
    department.opening.state === 'NOT_CHECKED'
      ? 'Opening not checked'
      : `Opening checked ${department.opening.checkedAt ? clock12(department.opening.checkedAt) : ''}, ${department.opening.differenceCount === 0 ? 'no difference' : `${department.opening.differenceCount} ${department.opening.differenceCount === 1 ? 'difference' : 'differences'}`}`;
  const delivery = department.delivery.state === 'CONFIRMED' ? 'Delivery confirmed' : department.delivery.state === 'WAITING' ? 'Delivery not confirmed' : 'No delivery today';
  const num = `text-right font-wds-mono text-[11px] leading-[14px] ${NAVY}`;
  const headCell = `${COL} text-right font-normal align-bottom`;

  return (
    <Page sheet={sheet} number={pageNumber} count={pageCount} cover={false}>
      {page.first ? (
        <div className="flex items-end justify-between gap-6">
          <div className="flex flex-col gap-[3px]">
            <span className={LABEL}>DEPARTMENT {department.position} OF {sheet.departments.length}</span>
            <h2 className={`m-0 text-[24px] font-semibold leading-[30px] ${NAVY}`}>{department.department.name}</h2>
          </div>
          <div className={`flex flex-col items-end gap-[3px] text-[12px] leading-4 ${BODY}`}>
            <span>{counted}</span>
            <span>{opening} · {delivery}</span>
          </div>
        </div>
      ) : (
        <p className={`m-0 mb-1 text-[12px] leading-[18px] ${BODY}`}>Department {department.department.name}, continued</p>
      )}

      <table className="mt-[22px] w-full table-fixed border-collapse" aria-label={`${department.department.name} figures`}>
        <colgroup>
          <col className="w-[20px]" />
          <col />
          <col className="w-[46px]" />
          <col className="w-[48px]" />
          <col className="w-[40px]" />
          <col className="w-[50px]" />
          <col className="w-[44px]" />
          <col className="w-[58px]" />
          <col className="w-[70px]" />
        </colgroup>
        <thead>
          <tr className="border-b-2 border-[#0B2A4A]">
            <th scope="col" className={`${COL} pb-2 text-left font-normal align-bottom`}>#</th>
            <th scope="col" className={`${COL} pb-2 pl-2 text-left font-normal align-bottom`}>ITEM</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>OPENING STOCK</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>RECEIVED</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>WASTE</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>CLOSING STOCK</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>USED TODAY</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>USED VALUE</th>
            <th scope="col" className={`${headCell} pb-2 pl-2`}>CLOSING VALUE</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((l) => {
            const corrected = l.correction !== null;
            const mark = corrected ? marks(correctedLines.indexOf(l) + 1) : '';
            return (
              <tr key={l.position} className={`border-b border-[#E3E8EE] ${corrected ? 'bg-[#FBF6E9]' : ''}`} style={{ height: SHEET_ROW }}>
                <td className={`pl-0.5 font-wds-mono text-[11px] leading-[14px] ${SLATE}`}>{l.position}</td>
                <td className="pl-2">
                  <div className="flex flex-col">
                    <span className={`text-[12px] font-medium leading-4 ${NAVY}`}>
                      {l.itemName}
                      {mark ? ` ${mark}` : ''}
                    </span>
                    <span className={`text-[10px] leading-3 ${SLATE}`}>{l.unit}</span>
                  </div>
                </td>
                <td className={`${num} pl-2`}>{qty(l.openingQty)}</td>
                <td className={`${num} pl-2`}>{qty(l.receivedQty)}</td>
                <td className={`${num} pl-2`}>{qty(l.wasteQty)}</td>
                <td className={`${num} pl-2`}><Corrected line={l} field="closing" /></td>
                <td className={`${num} pl-2`}><Corrected line={l} field="used" /></td>
                <td className={`${num} pl-2`}><Money value={l.usedValueKes} /></td>
                <td className={`${num} pl-2`}>{kes(l.closingValueKes)}</td>
              </tr>
            );
          })}
        </tbody>
        {page.last ? (
          <tfoot>
            <tr className="border-b-2 border-[#0B2A4A]">
              <td />
              <td colSpan={5} className={`py-3 pl-2 text-[12px] font-semibold leading-4 ${NAVY}`}>Department total (KES)</td>
              <td />
              <td className={`${num} py-3 pl-2 font-semibold`}>{kes(department.usedValueKes)}</td>
              <td className={`${num} py-3 pl-2 font-semibold`}>{kes(department.closingValueKes)}</td>
            </tr>
          </tfoot>
        ) : null}
      </table>

      {page.last && correctedLines.length > 0 ? (
        <div className={`mt-5 flex flex-col gap-[3px] text-[11px] leading-4 ${BODY}`}>
          {correctedLines.map((l, i) => {
            const c = l.correction;
            if (!c) return null;
            return (
              <p key={l.position} className="m-0">
                {marks(i + 1)} Corrected on {shortDayClock(c.at)} by the Branch Manager (reason: {CORRECTION_REASON_TEXT[c.reason].toLowerCase()}). The figure counted on {longDayYear(sheet.date).split(' ')[0]} is struck through.
              </p>
            );
          })}
        </div>
      ) : null}

      {page.closing ? <Closing sheet={sheet} /> : null}
    </Page>
  );
}

function Closing({ sheet }: { sheet: DaySheet }) {
  const rows = [sheet.departments.slice(0, 3), sheet.departments.slice(3)].filter((r) => r.length > 0);
  return (
    <>
      <section className="mt-[26px] flex flex-col gap-3" aria-label="Signatures">
        <span className={LABEL}>COUNTED AND SIGNED WITH PIN</span>
        {rows.map((row, ri) => (
          <div key={ri} className="flex gap-[18px]">
            {row.map((d) => (
              <div key={d.department.id} className={`flex flex-col gap-0.5 border-b border-[#D5DCE4] pb-1.5 ${ri === 0 ? 'min-w-0 flex-1' : 'w-[197px]'}`}>
                <span className={`font-wds-signature text-[24px] leading-7 ${NAVY}`}>{d.countedBy.name}</span>
                <span className={`text-[10px] leading-3 ${SLATE}`}>
                  {d.onBehalf ? `${d.department.name}, on behalf` : d.department.name} · {clock12(d.countedAt)}
                </span>
              </div>
            ))}
          </div>
        ))}
      </section>
      <div className="mt-[26px] flex items-end justify-between">
        <div className="flex flex-col gap-1">
          <span className={LABEL}>DAY CLOSED BY THE BRANCH MANAGER</span>
          <span className={`font-wds-signature text-[36px] leading-[42px] ${NAVY}`}>{sheet.closedBy.name}</span>
          <span className={`text-[11px] leading-[14px] ${SLATE}`}>
            Signed with PIN · {stamp(sheet.closedAt)}
            {sheet.correctedAt ? ` · correction signed ${stamp(sheet.correctedAt)}` : ''}
          </span>
        </div>
        <div className="flex items-end gap-3">
          <p className={`m-0 w-[90px] text-right text-[10px] leading-[14px] ${SLATE}`}>Scan to open {sheet.reference} in Wendo RMS</p>
          <QRCodeSVG value={sheet.qrUrl} size={84} marginSize={0} fgColor="#0B2A4A" aria-label={`QR code for ${sheet.reference}`} />
        </div>
      </div>
    </>
  );
}

function Sheets({ sheet }: { sheet: DaySheet }) {
  const footnotes = sheet.departments.map((d) => {
    const n = d.lines.filter((l) => l.correction).length;
    return n === 0 ? 0 : 20 + n * 19;
  });
  const plan = React.useMemo(() => paginateDaySheet(sheet.departments.map((d) => d.lines.length), footnotes), [sheet, footnotes.join(',')]);
  const count = plan.pages.length;
  return (
    <>
      {plan.pages.map((p, i) => {
        if (p.kind === 'cover') {
          return (
            <Page key={i} sheet={sheet} number={1} count={count} cover>
              <Cover sheet={sheet} pageOf={plan.departmentPages} />
            </Page>
          );
        }
        if (p.kind === 'closing') {
          return (
            <Page key={i} sheet={sheet} number={i + 1} count={count} cover={false}>
              <Closing sheet={sheet} />
            </Page>
          );
        }
        const department = sheet.departments[p.department];
        if (!department) return null;
        return <DepartmentPage key={i} sheet={sheet} department={department} page={p} pageNumber={i + 1} pageCount={count} />;
      })}
    </>
  );
}

/**
 * The printed day sheet (Paper B13b cover, B13c a department, B13d the signatures). A4 on a bare page: no sidebar and no top bar.
 * `?version=` prints that stored copy (the latest by default); a version printed "At the close" has no correction block and no strike.
 * Reading it writes nothing, and printing is not an audit event. The page opens the print dialog once the sheet is loaded.
 */
export function DaySheetPrintScreen({ dayId }: { dayId: string }) {
  const params = useSearchParams();
  const raw = Number(params.get('version'));
  const version = Number.isInteger(raw) && raw > 0 ? raw : undefined;
  const { data, status, reload } = useLoader<DaySheet>(`day-sheet:${dayId}:${version ?? 'latest'}`, () => branchDayDeskApi.sheet(dayId, version), 'We could not load this day sheet.');

  React.useEffect(() => {
    if (!data) return;
    const timer = window.setTimeout(() => window.print(), 400);
    return () => window.clearTimeout(timer);
  }, [data]);

  if (status === 'error') return <PrintError message="We could not load this day sheet. Close this tab and try again." onRetry={() => void reload()} />;
  if (!data) return <p role="status" className="flex min-h-screen items-center justify-center bg-white font-wds-sans text-wds-body-sm text-wds-text-secondary">Getting the day sheet…</p>;
  return (
    <PrintFrame>
      <Sheets sheet={data} />
    </PrintFrame>
  );
}
