'use client';

import * as React from 'react';
import { QRCodeSVG } from 'qrcode.react';

import { useLoader } from '../../_shared/hooks/use-async';
import { requisitionsApi } from '../_shared/services/requisitions-api';
import type { Person } from '../../_shared/types/wire';
import type { Print, PrintPageLine } from '../_shared/types/requisitions-contract';
import { clock } from '../_shared/lib/requisitions-words';

const TZ = 'Africa/Nairobi';
const fullDate = (iso: string): string => new Intl.DateTimeFormat('en-GB', { timeZone: TZ, day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(iso));
const stamp = (iso: string): string => `${fullDate(iso)}, ${new Intl.DateTimeFormat('en-GB', { timeZone: TZ, hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(iso))}`;
const MUTED = 'text-[#55626F]';
const RULE = 'border-[#D5DCE4]';

function Sheet({ children, page, pages, reference, generatedAt }: { children: React.ReactNode; page: number; pages: number; reference: string; generatedAt: string }) {
  return (
    <article className="relative mx-auto flex min-h-[1123px] w-[794px] max-w-full flex-col break-after-page bg-white px-12 pb-9 pt-0 font-wds-sans text-[#111111] shadow-wds-md print:shadow-none">
      <div aria-hidden className="-mx-12 h-[6px] bg-[#0B2A4A]" />
      {children}
      <footer className={`mt-auto flex items-end justify-between border-t pt-3 text-[10px] leading-3 ${RULE} ${MUTED}`}>
        <div className="flex flex-col gap-0.5">
          <span>Generated by Wendo RMS · Designed and developed by Lobster Technologies</span>
          <span className="font-wds-mono">{reference} · Generated {stamp(generatedAt)} · Page {page} of {pages}</span>
        </div>
        <div className="flex flex-col items-end gap-0.5">
          <span>lobstertechnologies.co.ke</span>
          <span>+254 113 176 613</span>
        </div>
      </footer>
    </article>
  );
}

function Masthead({ print, label, extra }: { print: Print; label: string; extra: React.ReactNode }) {
  return (
    <header className={`flex items-start justify-between border-b pb-[22px] pt-9 ${RULE}`}>
      <div className="flex items-center gap-3">
        <div className="size-[46px] rounded-full bg-cover bg-center" style={{ backgroundImage: 'url(/images/wendo-logo.jpg)' }} aria-hidden />
        <div className="flex flex-col">
          <span className="text-[20px] font-semibold leading-6 tracking-[-0.01em]">Wendo Coffee Bistro</span>
          <span className={`text-[12px] leading-4 ${MUTED}`}>{print.branch.name} · to the Central Store</span>
        </div>
      </div>
      <div className="flex flex-col items-end gap-1">
        <span className={`font-wds-mono text-[10px] leading-3 tracking-[0.14em] ${MUTED}`}>{label}</span>
        <span className="font-wds-mono text-[26px] font-semibold leading-8">{print.reference}</span>
        {extra}
      </div>
    </header>
  );
}

function Signature({ label, who, at }: { label: string; who: Person | null; at: string | null }) {
  return (
    <div className="flex w-[300px] flex-col gap-1">
      <span className={`font-wds-mono text-[10px] tracking-[0.1em] ${MUTED}`}>{label}</span>
      <div className="flex h-[50px] items-end border-b border-[#111111] pb-0.5">{who ? <span className="font-wds-signature text-[36px] leading-10">{who.name}</span> : null}</div>
      <span className="text-[12px] leading-4">{who ? `${who.name} · ${who.roleLabel}` : 'Waiting for approval'}</span>
      {who && at ? <span className={`text-[10px] leading-3 ${MUTED}`}>Signed with PIN · {stamp(at)}</span> : null}
    </div>
  );
}

function Qr({ print, caption }: { print: Print; caption: string }) {
  return (
    <div className="ml-auto flex flex-col items-center gap-1">
      <QRCodeSVG value={print.qrPayload} size={64} marginSize={0} aria-label={`QR code for ${print.reference}`} />
      <span className={`text-[10px] leading-3 ${MUTED}`}>{caption}</span>
    </div>
  );
}

const qtyText = (n: string): string => n;

function Lines({ lines, start, packed }: { lines: PrintPageLine[]; start: number; packed: boolean }) {
  return (
    <>
      {lines.map((l, i) => (
        <div key={`${l.n}-${i}`} className={`flex min-h-[42px] items-center border-b px-2 ${RULE} ${l.changed ? 'bg-[#F4F6F8]' : ''}`}>
          <span className={`w-8 font-wds-mono text-[11px] ${MUTED}`}>{start + i}</span>
          <span className="grow text-[14px]">
            {l.itemName}
            {l.changed ? <span> · changed</span> : null}
          </span>
          <span className={`w-16 text-right font-wds-mono text-[14px] ${l.changed ? 'line-through' : ''}`}>{qtyText(l.requestedQty)}</span>
          <span className={`w-20 text-right font-wds-mono text-[14px] ${l.changed ? 'font-semibold' : ''}`}>{qtyText(l.approvedQty)}</span>
          <span className={`w-24 pl-4 text-[13px] ${MUTED}`}>{l.unit}</span>
          {packed ? <span aria-hidden className="ml-auto mr-3 size-4 border border-[#111111]" /> : null}
        </div>
      ))}
    </>
  );
}

/**
 * The printed requisition (Paper step 17, A4 794 x 1123): a cover and one page per department, with NO money anywhere. The
 * cover carries the approval signature; each department page carries the packing lines with a Packed tick and three signing
 * lines. Standalone page (no sidebar), opened from the file. Printing is never a required step.
 */
export function RequisitionPrintScreen({ requisitionId }: { requisitionId: string }) {
  const { data, status } = useLoader<Print>(`print:${requisitionId}`, () => requisitionsApi.print(requisitionId), 'We could not load this requisition.');
  if (status === 'error') return <p className="flex min-h-screen items-center justify-center bg-white font-wds-sans text-wds-body-sm text-wds-text-secondary">We could not load this requisition. Close this tab and try again.</p>;
  if (!data) return <p role="status" className="flex min-h-screen items-center justify-center bg-white font-wds-sans text-wds-body-sm text-wds-text-secondary">Getting the requisition…</p>;
  const p = data;
  const pageCount = 1 + p.pages.length;
  const cycle = p.cycleLabel.split(' · ')[0] ?? p.cycleLabel;
  const added = p.cover.additionsCount;
  const totalLines = p.cover.departments.reduce((n, d) => n + d.lineCount, 0);
  const additionSigner = p.pages.flatMap((pg) => pg.additions).find((a) => a.approvedBy);

  return (
    <div className="min-h-screen bg-wds-neutral-100 py-6 print:bg-white print:py-0">
      <div className="mx-auto mb-4 flex w-[794px] max-w-full items-center justify-end px-1 print:hidden">
        <button type="button" onClick={() => window.print()} className="h-8 rounded-wds-sm bg-wds-primary px-4 font-wds-sans text-wds-body-sm font-medium text-white outline-none focus-visible:shadow-wds-ring">
          Print
        </button>
      </div>

      <Sheet page={1} pages={pageCount} reference={p.reference} generatedAt={p.generatedAt}>
        <Masthead print={p} label="REQUISITION" extra={<span className={`text-[12px] leading-4 ${MUTED}`}>{fullDate(p.startedAt)}</span>} />
        <section className={`flex gap-8 border-b py-5 ${RULE}`}>
          <div className="flex w-1/2 flex-col gap-1">
            <span className={`font-wds-mono text-[10px] leading-3 tracking-[0.1em] ${MUTED}`}>FROM</span>
            <span className="text-[18px] font-semibold leading-6">{p.branch.name} branch</span>
            <span className="text-[13px] leading-[18px]">{cycle} requisition, one for the whole branch</span>
            {p.approvedBy ? <span className="text-[13px] leading-[18px]">{p.approvedBy.roleLabel}: {p.approvedBy.name}</span> : null}
          </div>
          <div className={`w-px bg-[#D5DCE4]`} />
          <dl className="grid grow grid-cols-[auto_1fr] gap-x-6 gap-y-2 text-[13px]">
            <dt className={MUTED}>Cycle</dt><dd className="text-right">{cycle}</dd>
            <dt className={MUTED}>Started</dt><dd className="text-right">{clock(p.startedAt)}</dd>
            <dt className={MUTED}>Approved</dt><dd className="text-right">{p.approvedAt ? stamp(p.approvedAt) : 'Not yet'}</dd>
            <dt className={MUTED}>Departments</dt><dd className="text-right">{p.cover.departments.length} · {totalLines} lines{added ? ` + ${added} added` : ''}</dd>
          </dl>
        </section>
        <section className="flex flex-col py-4">
          <div className="flex h-8 items-center border-b-2 border-[#0B2A4A] px-2">
            <span className="w-8 font-wds-mono text-[10px] tracking-[0.08em]">#</span>
            <span className="grow font-wds-mono text-[10px] tracking-[0.08em]">DEPARTMENT</span>
            <span className="w-16 text-right font-wds-mono text-[10px] tracking-[0.08em]">LINES</span>
            <span className="w-40 pl-8 font-wds-mono text-[10px] tracking-[0.08em]">DISPATCH</span>
            <span className="w-12 text-right font-wds-mono text-[10px] tracking-[0.08em]">PAGE</span>
          </div>
          {p.cover.departments.map((d, i) => {
            const page = p.pages.find((pg) => pg.departmentId === d.departmentId);
            const pageAdded = page?.additions.reduce((n, a) => n + a.lines.length, 0) ?? 0;
            return (
              <div key={d.departmentId} className={`flex min-h-[54px] items-center border-b px-2 ${RULE}`}>
                <span className={`w-8 font-wds-mono text-[11px] ${MUTED}`}>{i + 1}</span>
                <div className="flex grow flex-col">
                  <span className="text-[15px]">{d.departmentName}</span>
                  {page?.askedBy && page.askedAt ? <span className={`text-[11px] ${MUTED}`}>Asked by the {page.askedBy.roleLabel} at {clock(page.askedAt)}</span> : null}
                </div>
                <span className="w-16 text-right font-wds-mono text-[14px]">{pageAdded ? `${d.lineCount} + ${pageAdded}` : d.lineCount}</span>
                <span className="w-40 pl-8 font-wds-mono text-[12px]">{d.dispatchReference ?? ''}</span>
                <span className="w-12 text-right font-wds-mono text-[14px]">{d.page}</span>
              </div>
            );
          })}
        </section>
        {p.cover.managerChanges.length > 0 ? (
          <section className="flex flex-col gap-1 py-2">
            <span className={`font-wds-mono text-[10px] tracking-[0.1em] ${MUTED}`}>CHANGED BY THE BRANCH MANAGER BEFORE APPROVAL</span>
            <p className="text-[13px] leading-[19px]">{p.cover.managerChanges.map((c) => `${c.departmentName}: ${c.itemName}, asked ${c.from}, approved ${c.to}.`).join(' ')}</p>
          </section>
        ) : null}
        {added > 0 ? (
          <section className="flex flex-col gap-1 py-2">
            <span className={`font-wds-mono text-[10px] tracking-[0.1em] ${MUTED}`}>ADDED AFTER APPROVAL</span>
            <p className="max-w-[640px] text-[13px] leading-[19px]">
              {p.pages
                .filter((pg) => pg.additions.length > 0)
                .map((pg) => `${pg.departmentName}: ${pg.additions.reduce((n, a) => n + a.lines.length, 0)} ${pg.additions.reduce((n, a) => n + a.lines.length, 0) === 1 ? 'line' : 'lines'} added${pg.additions[0] ? ` by the ${pg.departmentName} head at ${clock(pg.additions[0].addedAt)}` : ''}${pg.additions[0]?.approvedAt ? ` and approved at ${clock(pg.additions[0].approvedAt)}` : ''}. They are on the ${pg.departmentName} page.`)
                .join(' ')}
            </p>
          </section>
        ) : null}
        <section className={`mt-auto flex items-end gap-8 border-t py-5 ${RULE}`}>
          <Signature label="APPROVED BY" who={p.approvedBy} at={p.approvedAt} />
          {additionSigner ? <Signature label="ADDITION APPROVED BY" who={additionSigner.approvedBy} at={additionSigner.approvedAt} /> : null}
          <Qr print={p} caption={`Scan to open ${p.reference}`} />
        </section>
      </Sheet>

      {p.pages.map((pg, index) => {
        const addedCount = pg.additions.reduce((n, a) => n + a.lines.length, 0);
        const dispatchRef = p.cover.departments.find((d) => d.departmentId === pg.departmentId)?.dispatchReference;
        return (
          <Sheet key={pg.departmentId} page={index + 2} pages={pageCount} reference={p.reference} generatedAt={p.generatedAt}>
            <Masthead print={p} label={`REQUISITION · ${pg.departmentName.toUpperCase()}`} extra={dispatchRef ? <span className={`font-wds-mono text-[12px] ${MUTED}`}>Dispatch {dispatchRef}</span> : null} />
            <section className={`flex gap-8 border-b py-5 ${RULE}`}>
              <div className="flex w-1/2 flex-col gap-1">
                <span className={`font-wds-mono text-[10px] leading-3 tracking-[0.1em] ${MUTED}`}>DEPARTMENT</span>
                <span className="text-[18px] font-semibold leading-6">{pg.departmentName}</span>
                {pg.askedBy && pg.askedAt ? <span className="text-[13px] leading-[18px]">Asked by the {pg.askedBy.roleLabel}, {pg.askedBy.name}, at {clock(pg.askedAt)}</span> : null}
              </div>
              <div className="w-px bg-[#D5DCE4]" />
              <dl className="grid grow grid-cols-[auto_1fr] gap-x-6 gap-y-2 text-[13px]">
                <dt className={MUTED}>Approved</dt><dd className="text-right">{p.approvedAt ? clock(p.approvedAt) : 'Not yet'}</dd>
                <dt className={MUTED}>Lines</dt><dd className="text-right">{pg.lines.length}{addedCount ? ` + ${addedCount} added` : ''}</dd>
                {pg.deliverTo ? (<><dt className={MUTED}>Deliver to</dt><dd className="text-right">{pg.deliverTo}</dd></>) : null}
              </dl>
            </section>
            <section className="flex flex-col py-4">
              <div className="flex h-8 items-center border-b-2 border-[#0B2A4A] px-2">
                <span className="w-8 font-wds-mono text-[10px] tracking-[0.08em]">#</span>
                <span className="grow font-wds-mono text-[10px] tracking-[0.08em]">ITEM</span>
                <span className="w-16 text-right font-wds-mono text-[10px] tracking-[0.08em]">ASKED</span>
                <span className="w-20 text-right font-wds-mono text-[10px] tracking-[0.08em]">APPROVED</span>
                <span className="w-24 pl-4 font-wds-mono text-[10px] tracking-[0.08em]">UNIT</span>
                <span className="ml-auto w-14 text-right font-wds-mono text-[10px] tracking-[0.08em]">PACKED</span>
              </div>
              <Lines lines={pg.lines} start={1} packed />
              {pg.additions.map((a, ai) => (
                <React.Fragment key={`${a.addedAt}-${ai}`}>
                  <div className={`mt-3 border-b-2 border-[#0B2A4A] px-2 pb-1.5 pt-2 font-wds-mono text-[10px] tracking-[0.08em]`}>
                    ADDED AFTER APPROVAL{a.approvedBy && a.approvedAt ? ` · APPROVED BY THE ${a.approvedBy.roleLabel.toUpperCase()} AT ${new Intl.DateTimeFormat('en-GB', { timeZone: TZ, hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(a.approvedAt))}` : ' · WAITING FOR APPROVAL'}
                  </div>
                  <Lines lines={a.lines} start={pg.lines.length + pg.additions.slice(0, ai).reduce((n, x) => n + x.lines.length, 0) + 1} packed />
                </React.Fragment>
              ))}
            </section>
            <section className={`mt-auto flex items-end gap-6 border-t py-5 ${RULE}`}>
              {['PACKED BY', 'SIGNED BY', 'CARRIED BY'].map((label, i) => (
                <div key={label} className="flex w-[170px] flex-col gap-1">
                  <span className={`font-wds-mono text-[10px] tracking-[0.1em] ${MUTED}`}>{label}</span>
                  <div className="h-[50px] border-b border-[#111111]" />
                  <span className={`text-[10px] ${MUTED}`}>{['Name and date', 'Name and date (the packer signs)', 'Driver or vehicle'][i]}</span>
                </div>
              ))}
              <Qr print={p} caption={dispatchRef ? `Scan to open ${dispatchRef}` : `Scan to open ${p.reference}`} />
            </section>
          </Sheet>
        );
      })}
    </div>
  );
}
