import { Router } from 'express';
import healthRoutes from './health-routes';
import authRoutes from './auth-routes';
import branchRoutes from './branch-routes';
import staffRoutes from './staff-routes';
import menuRoutes from './menu-routes';
import orderRoutes from './order-routes';
import prepTicketRoutes from './prep-ticket-routes';
import deliveryZoneRoutes from './delivery-zone-routes';
import shiftRoutes from './shift-routes';
import shiftAssignmentRoutes from './shift-assignment-routes';
import clockRoutes from './clock-routes';
import reportRoutes from './report-routes';
import incidentRoutes from './incident-routes';
import printRoutes from './print-routes';
import houseAccountRoutes from './house-account-routes';
import corporateAccountRoutes from './corporate-account-routes';
import customerCreditRoutes from './customer-credit-routes';
import otherIncomeRoutes from './other-income-routes';
import houseAccountAuthRoutes from './house-account-auth-routes';
import staffDiscountAuthRoutes from './staff-discount-auth-routes';
import discountRoutes from './discount-routes';
import customerDiscountAuthRoutes from './customer-discount-auth-routes';
import orderCancellationAuthRoutes from './order-cancellation-auth-routes';
import commsRoutes from './comms-routes';
import hrRoutes from './hr-routes';
import staffTransferRoutes from './staff-transfer-routes';
import payslipRoutes from './payslip-routes';
import orderCorrectionRoutes from './order-correction-routes';
import locationRoutes from './location-routes';
import departmentRoutes from './department-routes';
import inventoryRoutes from '../modules/inventory/inventory-routes';
import receivingRoutes from '../modules/inventory/receiving-routes';
import prepRoutes from '../modules/inventory/prep-routes';

const apiRouter = Router();

apiRouter.use(healthRoutes);
apiRouter.use(authRoutes);
apiRouter.use(branchRoutes);
apiRouter.use(staffRoutes);
apiRouter.use(menuRoutes);
apiRouter.use(orderRoutes);
apiRouter.use(prepTicketRoutes);
apiRouter.use(deliveryZoneRoutes);
apiRouter.use(shiftRoutes);
apiRouter.use(shiftAssignmentRoutes);
apiRouter.use(clockRoutes);
apiRouter.use(reportRoutes);
apiRouter.use(incidentRoutes);
apiRouter.use(printRoutes);
apiRouter.use(houseAccountRoutes);
apiRouter.use(corporateAccountRoutes);
apiRouter.use(customerCreditRoutes);
apiRouter.use(otherIncomeRoutes);
apiRouter.use(houseAccountAuthRoutes);
apiRouter.use(staffDiscountAuthRoutes);
apiRouter.use(discountRoutes);
apiRouter.use(customerDiscountAuthRoutes);
apiRouter.use(orderCancellationAuthRoutes);
apiRouter.use(commsRoutes);
apiRouter.use(hrRoutes);
apiRouter.use(staffTransferRoutes);
apiRouter.use(payslipRoutes);
apiRouter.use(orderCorrectionRoutes);
apiRouter.use(locationRoutes);
apiRouter.use(departmentRoutes);
apiRouter.use(inventoryRoutes);
apiRouter.use(receivingRoutes);
apiRouter.use(prepRoutes);

export default apiRouter;
