#!/usr/bin/env bash
# Parallel-lane tooling: one git worktree, database, Redis and browser profile per lane.
# Full explanation: docs/PARALLEL_WORKFLOW.md
#
# Usage:
#   scripts/lane.sh template build|refresh|status   shared seeded template database
#   scripts/lane.sh up <N> <branch>                 create or re-check lane N (1-3)
#   scripts/lane.sh down <N>                        remove lane N (refuses if work is uncommitted)
#   scripts/lane.sh list                            one line per lane
#   scripts/lane.sh status [N]                      detail for one lane (or all) + shared services
#
# Lane N uses: frontend 3100+N, API 4100+N, worker 4150+N, Redis 6400+N, browser debug 9220+N.
# The main stack (3000, 4000, 5433, 6379) is never touched. This script never kills a process.

set -euo pipefail

# ── Settings (override with env vars) ────────────────────────────────────────
LANES_ROOT="${LANES_ROOT:-$HOME/Projects/V3-RMS-lanes}"
PG_CONTAINER="${LANE_PG_CONTAINER:-wendo-postgres}"
PG_USER="${LANE_PG_USER:-wendo_user}"
SOURCE_DB="${LANE_SOURCE_DB:-wendo_rms}"
TEMPLATE_DB="${LANE_TEMPLATE_DB:-wendo_rms_template}"
REDIS_IMAGE="${LANE_REDIS_IMAGE:-redis:7-alpine}"
PROFILES_ROOT="${LANE_PROFILES_ROOT:-$HOME/.cache/wendo-lanes}"
MAX_LANE="${LANE_MAX:-3}" # raise with LANE_MAX=6 when lanes 1-3 are taken by other work; ports follow the lane number

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THIS_REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
# The first entry of `git worktree list` is the main checkout, which holds the owner's real env files.
MAIN_REPO="$(git -C "$THIS_REPO" worktree list --porcelain | awk '/^worktree /{print substr($0,10); exit}')"
SOURCE_BACKEND_ENV="${LANE_SOURCE_BACKEND_ENV:-$MAIN_REPO/backend/.env}"
SOURCE_FRONTEND_ENV="${LANE_SOURCE_FRONTEND_ENV:-$MAIN_REPO/frontend/.env}"

die() { echo "lane: $*" >&2; exit 1; }
say() { echo "lane: $*"; }

# ── Per-lane values ──────────────────────────────────────────────────────────
lane_vars() {
  N="$1"
  [[ "$N" =~ ^[0-9]+$ ]] && (( N >= 1 && N <= MAX_LANE )) || die "lane number must be 1-$MAX_LANE (got '$1')"
  FE_PORT=$((3100 + N)); API_PORT=$((4100 + N)); WORKER_PORT=$((4150 + N))
  REDIS_PORT=$((6400 + N)); DEBUG_PORT=$((9220 + N))
  LANE_DIR="$LANES_ROOT/lane-$N"
  LANE_DB="wendo_rms_lane$N"
  REDIS_NAME="wendo-lane-$N-redis"
  LANE_HOST="lane$N.localhost"
  PROFILE_DIR="$PROFILES_ROOT/lane-$N"
}

# ── Helpers ──────────────────────────────────────────────────────────────────
listening() { [ -n "$(ss -ltnH "sport = :$1" 2>/dev/null)" ]; }

pg() { docker exec -i "$PG_CONTAINER" psql -U "$PG_USER" -d postgres -v ON_ERROR_STOP=1 -Atq "$@"; }
db_exists() { [ "$(pg -c "select 1 from pg_database where datname='$1'")" = "1" ]; }

need_postgres() {
  [ "$(docker inspect -f '{{.State.Running}}' "$PG_CONTAINER" 2>/dev/null || true)" = "true" ] \
    || die "Postgres container '$PG_CONTAINER' is not running (cd $MAIN_REPO && docker compose up -d postgres)"
}

# Copy KEY=value lines from $1, dropping the keys listed in $3.. , then append the overrides in $2 (a file).
write_env() {
  local src="$1" overrides="$2" dest="$3"; shift 3
  local pattern; pattern="^($(IFS='|'; echo "$*"))="
  {
    echo "# Generated by scripts/lane.sh for this lane. Do not commit. Re-run 'lane.sh up' to regenerate."
    [ -f "$src" ] && grep -v -E "$pattern" "$src" | grep -v '^# Generated by scripts/lane.sh' || true
    cat "$overrides"
  } > "$dest.tmp"
  chmod 600 "$dest.tmp"; mv "$dest.tmp" "$dest"
}

# Connection URL for the lane DB: same credentials/host as the owner's backend/.env, only the database name changes.
lane_database_url() {
  local line url base query
  line="$(grep -E '^DATABASE_URL=' "$SOURCE_BACKEND_ENV" | head -n1 || true)"
  [ -n "$line" ] || die "DATABASE_URL not found in $SOURCE_BACKEND_ENV"
  url="${line#DATABASE_URL=}"
  url="${url//@postgres:5432/@localhost:5433}"   # compose-style host -> host-published port
  base="${url%%\?*}"; query="${url#"$base"}"
  echo "${base%/*}/$1$query"
}

# The script's own generated files do not count as work (they are gitignored once this tooling is on main).
is_dirty() { [ -n "$(git -C "$1" status --porcelain -- . ':!/.lane' ':!/.mcp.json' 2>/dev/null)" ]; }

# ── template ─────────────────────────────────────────────────────────────────
cmd_template() {
  need_postgres
  local sub="${1:-status}"
  case "$sub" in
    status)
      if db_exists "$TEMPLATE_DB"; then
        local n; n="$(docker exec -i "$PG_CONTAINER" psql -U "$PG_USER" -d "$TEMPLATE_DB" -Atqc 'select count(*) from _prisma_migrations')"
        local mdir="$MAIN_REPO/backend/prisma/schema/migrations"
        [ -d "$mdir" ] || mdir="$MAIN_REPO/backend/prisma/migrations" # before the folder move reaches the main checkout
        local have; have="$(find "$mdir" -mindepth 1 -maxdepth 1 -type d | wc -l)"
        say "template '$TEMPLATE_DB' exists: $n migrations applied (this repo has $have migration folders)"
      else
        say "template '$TEMPLATE_DB' does not exist. Build it with: scripts/lane.sh template build"
      fi ;;
    build|refresh)
      db_exists "$SOURCE_DB" || die "source database '$SOURCE_DB' not found"
      if db_exists "$TEMPLATE_DB"; then
        [ "$sub" = refresh ] || die "template exists already; use 'template refresh' to rebuild it"
        pg -c "alter database \"$TEMPLATE_DB\" is_template false" -c "drop database \"$TEMPLATE_DB\""
      fi
      say "copying '$SOURCE_DB' into template '$TEMPLATE_DB' (pg_dump, no lock on the source) ..."
      pg -c "create database \"$TEMPLATE_DB\""
      docker exec "$PG_CONTAINER" pg_dump -U "$PG_USER" --no-owner --no-privileges "$SOURCE_DB" \
        | docker exec -i "$PG_CONTAINER" psql -U "$PG_USER" -d "$TEMPLATE_DB" -q -v ON_ERROR_STOP=1 -o /dev/null
      pg -c "alter database \"$TEMPLATE_DB\" is_template true"
      cmd_template status ;;
    *) die "usage: lane.sh template build|refresh|status" ;;
  esac
}

# ── up ───────────────────────────────────────────────────────────────────────
write_browser_config() {
  # Project-scoped MCP config: overrides the same-named user-level servers for sessions started in this worktree.
  local dburl; dburl="$(lane_database_url "$LANE_DB")"
  mkdir -p "$PROFILE_DIR/chrome" "$PROFILE_DIR/playwright" "$LANE_DIR/.lane"
  cat > "$LANE_DIR/.mcp.json" <<JSON
{
  "mcpServers": {
    "chrome-devtools": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "chrome-devtools-mcp@latest", "--userDataDir", "$PROFILE_DIR/chrome"],
      "env": {}
    },
    "playwright": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@playwright/mcp@latest", "--user-data-dir", "$PROFILE_DIR/playwright", "--output-dir", "$LANE_DIR/.lane/playwright-output"],
      "env": {}
    },
    "postgres": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-postgres", "$dburl"],
      "env": {}
    }
  }
}
JSON
  chmod 600 "$LANE_DIR/.mcp.json"
}

cmd_up() {
  [ $# -eq 2 ] || die "usage: lane.sh up <N> <branch>"
  lane_vars "$1"; local branch="$2"
  git check-ref-format --branch "$branch" >/dev/null 2>&1 || die "'$branch' is not a valid branch name"
  [ "$branch" != main ] || die "a lane must work on its own branch, not main"
  need_postgres
  db_exists "$TEMPLATE_DB" || die "template database missing. Run: scripts/lane.sh template build"
  [ -f "$SOURCE_BACKEND_ENV" ] || die "owner's backend env not found at $SOURCE_BACKEND_ENV"
  command -v docker >/dev/null && command -v pnpm >/dev/null || die "docker and pnpm are required"

  # Refuse ports that are busy and not ours. A lane that already exists may have its own servers running.
  local existing=no; [ -f "$LANE_DIR/.lane/lane.env" ] && existing=yes
  local p
  if [ "$existing" = no ]; then
    for p in $FE_PORT $API_PORT $WORKER_PORT $REDIS_PORT; do
      ! listening "$p" || die "port $p is already listening; lane $N cannot start (is another lane using it?)"
    done
  fi
  local redis_state; redis_state="$(docker ps -a --filter "name=^${REDIS_NAME}\$" --format '{{.State}}')"
  case "$redis_state" in running) redis_state=true ;; "") redis_state=none ;; *) redis_state=false ;; esac
  if [ "$redis_state" != true ]; then
    ! listening "$REDIS_PORT" || die "port $REDIS_PORT is already listening and is not lane $N's Redis"
  fi

  # 1. Worktree
  git -C "$MAIN_REPO" fetch --quiet origin || say "warning: git fetch failed, using local refs"
  mkdir -p "$LANES_ROOT"
  if [ -d "$LANE_DIR" ]; then
    git -C "$LANE_DIR" rev-parse --git-dir >/dev/null 2>&1 || die "$LANE_DIR exists but is not a git worktree"
    local cur; cur="$(git -C "$LANE_DIR" rev-parse --abbrev-ref HEAD)"
    [ "$cur" = "$branch" ] || die "lane $N already holds branch '$cur', not '$branch'. Run 'lane.sh down $N' first."
    say "worktree $LANE_DIR already on $branch"
  elif git -C "$MAIN_REPO" show-ref --verify --quiet "refs/heads/$branch"; then
    git -C "$MAIN_REPO" worktree add "$LANE_DIR" "$branch" >/dev/null
  elif git -C "$MAIN_REPO" show-ref --verify --quiet "refs/remotes/origin/$branch"; then
    git -C "$MAIN_REPO" worktree add --no-track -b "$branch" "$LANE_DIR" "origin/$branch" >/dev/null
  else
    git -C "$MAIN_REPO" worktree add --no-track -b "$branch" "$LANE_DIR" origin/main >/dev/null
  fi
  mkdir -p "$LANE_DIR/.lane"

  # 2. Database (cloned from the template)
  if db_exists "$LANE_DB"; then
    say "database $LANE_DB already exists"
  else
    pg -c "create database \"$LANE_DB\" template \"$TEMPLATE_DB\""
    say "created database $LANE_DB from $TEMPLATE_DB"
  fi

  # 3. Redis (own container, loopback only, small and non-persistent)
  case "$redis_state" in
    true) say "redis $REDIS_NAME already running" ;;
    false) docker start "$REDIS_NAME" >/dev/null; say "started $REDIS_NAME" ;;
    none)
      docker run -d --name "$REDIS_NAME" --label "wendo.lane=$N" --memory 64m \
        -p "127.0.0.1:$REDIS_PORT:6379" "$REDIS_IMAGE" \
        redis-server --save "" --appendonly no --maxmemory 48mb >/dev/null
      say "started $REDIS_NAME on 127.0.0.1:$REDIS_PORT" ;;
  esac

  # 4. Env files. Secrets are copied from the owner's env; only the lane-specific keys are replaced.
  local ov; ov="$(mktemp)"
  cat > "$ov" <<ENV
NODE_ENV=development
PORT=$API_PORT
FRONTEND_ORIGIN=http://$LANE_HOST:$FE_PORT
COOKIE_DOMAIN=
DATABASE_URL=$(lane_database_url "$LANE_DB")
REDIS_URL=redis://127.0.0.1:$REDIS_PORT
START_BULLMQ_WORKERS=false
ENV
  write_env "$SOURCE_BACKEND_ENV" "$ov" "$LANE_DIR/backend/.env" NODE_ENV PORT FRONTEND_ORIGIN COOKIE_DOMAIN DATABASE_URL REDIS_URL START_BULLMQ_WORKERS
  cat > "$ov" <<ENV
NEXT_PUBLIC_API_URL=http://$LANE_HOST:$API_PORT/api/v1
NEXT_PUBLIC_SOCKET_URL=http://$LANE_HOST:$API_PORT
NEXT_PUBLIC_COOKIE_DOMAIN=
ENV
  write_env "$SOURCE_FRONTEND_ENV" "$ov" "$LANE_DIR/frontend/.env" NEXT_PUBLIC_API_URL NEXT_PUBLIC_SOCKET_URL NEXT_PUBLIC_COOKIE_DOMAIN
  rm -f "$ov"

  # 5. Browser tools config
  write_browser_config

  # 6. Lane record
  cat > "$LANE_DIR/.lane/lane.env" <<REC
LANE=$N
BRANCH=$branch
FE_PORT=$FE_PORT
API_PORT=$API_PORT
WORKER_PORT=$WORKER_PORT
REDIS_PORT=$REDIS_PORT
DEBUG_PORT=$DEBUG_PORT
DATABASE=$LANE_DB
REDIS_CONTAINER=$REDIS_NAME
HOST=$LANE_HOST
REC

  # 7. Dependencies, Prisma client, pending migrations (lane database only)
  say "installing dependencies (pnpm store is shared, so this is mostly hard links) ..."
  (cd "$LANE_DIR/backend" && pnpm install --frozen-lockfile --silent && pnpm exec prisma generate >/dev/null)
  (cd "$LANE_DIR/frontend" && pnpm install --frozen-lockfile --silent)
  say "applying this branch's migrations to $LANE_DB ..."
  (cd "$LANE_DIR/backend" && pnpm exec prisma migrate deploy 2>&1 | tail -3)

  print_commands
}

print_commands() {
  cat <<OUT

Lane $N is ready.
  worktree   $LANE_DIR   (branch $(git -C "$LANE_DIR" rev-parse --abbrev-ref HEAD))
  database   $LANE_DB   redis $REDIS_NAME (127.0.0.1:$REDIS_PORT)
  frontend   http://$LANE_HOST:$FE_PORT      API http://$LANE_HOST:$API_PORT/api/v1

Start (each in its own terminal; they are NOT started for you):
  API:       cd $LANE_DIR/backend  && pnpm dev
  Worker:    cd $LANE_DIR/backend  && START_BULLMQ_WORKERS=true PORT=$WORKER_PORT pnpm exec tsx src/server.ts   (optional; skip it to save RAM)
  Frontend:  cd $LANE_DIR/frontend && PORT=$FE_PORT pnpm dev

Open the lane at http://$LANE_HOST:$FE_PORT (not localhost: each lane host keeps its own login cookies).
Start the agent session from $LANE_DIR so it picks up the lane's .mcp.json (browser profile + database).
OUT
}

# ── down ─────────────────────────────────────────────────────────────────────
cmd_down() {
  [ $# -ge 1 ] || die "usage: lane.sh down <N>"
  lane_vars "$1"; shift
  need_postgres
  if [ -d "$LANE_DIR" ]; then
    git -C "$LANE_DIR" rev-parse --git-dir >/dev/null 2>&1 || die "$LANE_DIR is not a git worktree; not touching it"
    if is_dirty "$LANE_DIR"; then
      git -C "$LANE_DIR" status --short -- . ':!/.lane' ':!/.mcp.json' | head -20 >&2
      die "lane $N has uncommitted or untracked files (listed above). Commit or move them first."
    fi
  fi
  for p in $FE_PORT $API_PORT $WORKER_PORT; do
    ! listening "$p" || die "port $p is still listening: stop lane $N's servers yourself first (this script never kills processes)"
  done

  local branch=""
  [ -d "$LANE_DIR" ] && branch="$(git -C "$LANE_DIR" rev-parse --abbrev-ref HEAD)"

  if docker inspect "$REDIS_NAME" >/dev/null 2>&1; then
    [ "$(docker inspect -f '{{index .Config.Labels "wendo.lane"}}' "$REDIS_NAME")" = "$N" ] \
      || die "container $REDIS_NAME does not carry this lane's label; not removing it"
    docker rm -f "$REDIS_NAME" >/dev/null; say "removed $REDIS_NAME"
  fi
  if db_exists "$LANE_DB"; then
    pg -c "drop database \"$LANE_DB\"" >/dev/null || die "could not drop $LANE_DB (still has connections, e.g. Prisma Studio?)"
    say "dropped database $LANE_DB"
  fi
  if [ -d "$LANE_DIR" ]; then
    # --force is safe here: is_dirty above already proved nothing but the script's own files is uncommitted.
    git -C "$MAIN_REPO" worktree remove --force "$LANE_DIR" && say "removed worktree $LANE_DIR"
  fi
  git -C "$MAIN_REPO" worktree prune
  rm -rf "$PROFILE_DIR"
  [ -z "$branch" ] || say "branch '$branch' is kept (delete it yourself once merged)"
}

# ── list / status ────────────────────────────────────────────────────────────
lane_line() {
  lane_vars "$1"
  if [ ! -f "$LANE_DIR/.lane/lane.env" ]; then printf '%s  %-4s  %s\n' "lane $N" "free" "(ports fe $FE_PORT api $API_PORT redis $REDIS_PORT)"; return; fi
  local br; br="$(git -C "$LANE_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
  local d=clean; is_dirty "$LANE_DIR" && d=DIRTY
  local f=down a=down r=down db=no
  listening "$FE_PORT" && f=up; listening "$API_PORT" && a=up
  [ "$(docker inspect -f '{{.State.Running}}' "$REDIS_NAME" 2>/dev/null || true)" = true ] && r=up
  db_exists "$LANE_DB" 2>/dev/null && db=yes
  printf '%s  %-4s  %-34s  fe:%s api:%s redis:%s db:%s  %s\n' "lane $N" "used" "$br" "$f" "$a" "$r" "$db" "$d"
}

cmd_list() { local i; for i in $(seq 1 $MAX_LANE); do lane_line "$i"; done; }

cmd_status() {
  need_postgres
  say "shared: Postgres $PG_CONTAINER is up"
  cmd_template status
  if [ $# -ge 1 ]; then lane_line "$1"; lane_vars "$1"; [ -f "$LANE_DIR/.lane/lane.env" ] && { echo; cat "$LANE_DIR/.lane/lane.env"; }
  else cmd_list; fi
  echo; free -h | awk 'NR<=2'
}

# ── dispatch ─────────────────────────────────────────────────────────────────
case "${1:-}" in
  template) shift; cmd_template "$@" ;;
  up)       shift; cmd_up "$@" ;;
  down)     shift; cmd_down "$@" ;;
  list)     cmd_list ;;
  status)   shift; cmd_status "$@" ;;
  *) sed -n 2,13p "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
